<?php

namespace Admin\ApiRestBundle\Entity;

/**
 * CategorysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorysRepository extends \Doctrine\ORM\EntityRepository
{
}
