<?php

namespace Admin\ApiRestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RequestsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestsRepository extends EntityRepository
{
    public function findRequestsById($id){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT u FROM ApiRestBundle:Requests u WHERE u.id = :id");
        $query->setParameter('id',$id);
        return $query->getArrayResult();
    }

    public function findAllRequests(){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT u FROM ApiRestBundle:Requests u");
        return $query->getArrayResult();
    }
}
