<?php

namespace Admin\ApiRestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SalesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalesRepository extends EntityRepository
{
    public function findSalesById($id){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT u FROM ApiRestBundle:Sales u WHERE u.id = :id");
        $query->setParameter('id',$id);
        return $query->getArrayResult();
    }

    public function findAllSales(){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT u FROM ApiRestBundle:Sales u");
        return $query->getArrayResult();
    }
}
