<?php

namespace Admin\ApiRestBundle\Entity;
 use Doctrine\ORM\EntityRepository;
/**
 * ImpuestosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImpuestosRepository extends EntityRepository
{
    public function findImpuestosById($id){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT u FROM ApiRestBundle:Impuestos u WHERE u.id = :id");
        $query->setParameter('id',$id);
        return $query->getArrayResult();
    }

    public function findAllImpuestos(){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT u FROM ApiRestBundle:Impuestos u");
        return $query->getArrayResult();
    }
}
