<?php

namespace Admin\ApiRestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OffersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffersRepository extends EntityRepository
{
    public function findOffersById($id){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT u FROM ApiRestBundle:Offers u WHERE u.id = :id");
        $query->setParameter('id',$id);
        return $query->getArrayResult();
    }

    public function findAllOffers(){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT u FROM ApiRestBundle:Offers u");
        return $query->getArrayResult();
    }
}
