<?php

namespace Admin\ApiRestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProvidersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProvidersRepository extends EntityRepository
{
    public function findProvidersById($id){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT u FROM ApiRestBundle:Providers u WHERE u.id = :id");
        $query->setParameter('id',$id);
        return $query->getArrayResult();
    }

    public function findAllProviders(){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT u FROM ApiRestBundle:Providers u");
        return $query->getArrayResult();
    }
}
