api_rest_categoria:
    type: rest
    resource: "@ApiRestBundle/Controller/CategorysController.php"
    name_prefix: api_categorias_

api_rest_articles:
    type: rest
    resource: "@ApiRestBundle/Controller/ArticlesController.php"
    name_prefix:  api_articles_

api_rest_users:
    type: rest
    resource: "@ApiRestBundle/Controller/UsersController.php"
    name_prefix: api_users_

api_rest_offer:
    type: rest
    resource: "@ApiRestBundle/Controller/OffersController.php"
    name_prefix: api_offers_

api_rest_promotion:
    type: rest
    resource: "@ApiRestBundle/Controller/PromotionsController.php"
    name_prefix: api_promotions_

api_rest_provider:
    type: rest
    resource: "@ApiRestBundle/Controller/ProvidersController.php"
    name_prefix: api_providers_

api_rest_request:
    type: rest
    resource: "@ApiRestBundle/Controller/RequestsController.php"
    name_prefix: api_requests_

api_rest_sale:
    type: rest
    resource: "@ApiRestBundle/Controller/SalesController.php"
    name_prefix: api_sales_

api_rest_shopcar:
    type: rest
    resource: "@ApiRestBundle/Controller/ShopcarsController.php"
    name_prefix: api_shopcars_

api_rest_impuesto:
    type: rest
    resource: "@ApiRestBundle/Controller/ImpuestosController.php"
    name_prefix: api_impuestos_

api_rest_client:
    type: rest
    resource: "@ApiRestBundle/Controller/ClientsController.php"
    name_prefix: api_clients_

api_rest_administrator:
    type: rest
    resource: "@ApiRestBundle/Controller/AdministratorsController.php"
    name_prefix: api_administrators_